---
title: 'Project 3: Wildfire Data'
author: "Steph Camino"
date: '2022-07-19'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Welcome! This is the data description for the wildfire data used in my project 3 app. Like mentioned on the About page in the app, this data was provided by a Regional Fire Ecologist for the National Park Service and was exported by the U.S Geological Survey. 

# Data Description

* stem_c_ha: Stem Carbon
  * Stem carbon is the total dry weight of living matter in each plot measured in kilograms and multiplied by 0.5.
  * This is used as our response for the following exploratory data analysis and modeling.
  
* park: Klamath network parks
  * Park is a categorical variable which includes 4 different parks in Interior Regions 8, 9, 10, and 12. They are:
    * CRLA: Crater Lake National Park
    * LAVO: Lassen Volcanic National Park
    * LABE: Lava Beds National Monument
    * WHIS: Whiskeytown National Recreation Area
    
* n_tree_ha: Tree Density
  * The number of live trees in each plot.
  
* basal_area_ha: Basal Area
  * The cross sectional or total area (m 2) of stump surface within the plot measured.
  
* Year
  * The year the measurement occurred. 
  
* Month
  * The month the measurement occurred.
  
* Day
  * The day the measurement occurred. 
